services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ugm\SwooleGrpc\:
        resource: '../../*'

    Ugm\SwooleGrpc\Server\HttpFoundation\FromGrpcRequestFactory:
        decorates: K911\Swoole\Bridge\Symfony\HttpFoundation\RequestFactoryInterface

    Ugm\SwooleGrpc\Server\HttpFoundation\GrpcResponseProcessor:
        decorates: K911\Swoole\Bridge\Symfony\HttpFoundation\ResponseProcessorInterface

    ugm.grpc_bundle.add_grpc_request_format_listener:
        class: Symfony\Component\HttpKernel\EventListener\AddRequestFormatsListener
        arguments:
            - proto:
                - 'application/grpc'
                - 'application/grpc+proto'
                - 'application/vnd.google.protobuf'
                - 'application/x-protobuf'
                - 'application/x-google-protobuf'
