services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ugm\SwooleGrpc\:
        resource: '../../*'

    K911\Swoole\Bridge\Symfony\HttpFoundation\RequestFactoryInterface:
        class: Ugm\SwooleGrpc\Server\HttpFoundation\FromGrpcRequestFactory

    Ugm\SwooleGrpc\Server\HttpFoundation\GrpcResponseProcessor:
        decorates: K911\Swoole\Bridge\Symfony\HttpFoundation\ResponseProcessorInterface
