services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ugm\SwooleGrpc\:
        resource: '../../*'

    Ugm\SwooleGrpc\Server\HttpFoundation\FromGrpcRequestFactory:
        decorates: K911\Swoole\Bridge\Symfony\HttpFoundation\RequestFactoryInterface

    Ugm\SwooleGrpc\Server\HttpFoundation\GrpcResponseProcessor:
        decorates: K911\Swoole\Bridge\Symfony\HttpFoundation\ResponseProcessorInterface
